import type { Metadata } from 'next'
import { Commissioner } from 'next/font/google'
import './globals.css'
import Providers from '@/components/providers/Providers'

const commissioner =
  Commissioner({
    subsets: ['latin'],
    axes: ['FLAR', 'VOLM', 'slnt']
  })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${commissioner.className} bg-primary`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
